export default {
  "complex": {
    "descriptionInformation": "Description information",
    "useInterface": "When using PutObject interface, if a parameter prefixed with **x-oss-meta-*** is configured, the parameter is regarded as metadata."
  },
  "simple": {
    "representativeCreation": "A resource property field that represents the time of creation",
    "creationTime": "Creation time",
    "representativeResource3": "A resource property field that represents the level 1 ID of the resource",
    "resourceLevel1": "Resource level ID",
    "representativeResource2": "A resource property field that represents the resource name",
    "resourceName": "Resource name",
    "representativeResource": "A resource property field that represents a resource group",
    "resourceGroup": "Resource group ID",
    "serveAsAGuarantee": "Used to ensure that the request is idempotent. This parameter value is generated by the client to ensure that it is unique across requests. The value contains only ASCII characters and a maximum of 64 characters"
  }
}